<?php
// queue_list/live_queue.php
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

$pageTitle = "Live Queue Display";

$cssPath = __DIR__ . '/../assets/css/style.css';
$cssVersion = file_exists($cssPath) ? filemtime($cssPath) : time();

$baseUrl = defined('BASE_URL') ? BASE_URL : '..';
$extraCss = '<link rel="stylesheet" href="' . $baseUrl . '/assets/css/style.css?v=' . $cssVersion . '">';

require_once __DIR__ . '/../includes/header.php';
?>

<div class="portal-bg min-vh-100 d-flex flex-column justify-content-between">

  <div class="live-queue-wrapper flex-grow-1 position-relative z-1">

    <!-- TOP HEADER -->
    <header class="queue-nav-header d-flex align-items-center justify-content-between">
      <!-- Left: Logo & Branding -->
      <div class="d-flex align-items-center gap-3">
        <a href="<?= $baseUrl; ?>/index.php" class="d-flex align-items-center gap-3 text-decoration-none text-white">
          <img src="<?= $baseUrl; ?>/assets/img/ccc-logo.png" alt="CCC Logo" class="queue-logo"
            onerror="this.style.display='none'">
          <div>
            <h3 class="fw-bold mb-0 text-white tracking-tight fs-4">City College of Calamba</h3>
            <p class="small text-white-50 mb-0 fw-bold tracking-widest text-uppercase" style="font-size: 0.65rem;">STUDENT
              SERVICE QUEUE SYSTEM</p>
          </div>
        </a>
      </div>

      <!-- Right: Live Date & Clock -->
      <div class="d-flex align-items-center gap-3 text-white">
        <div class="d-flex align-items-center gap-2 fw-bold small text-uppercase"
          style="font-size: 0.85rem; opacity: 0.9;">
          <i class="bi bi-calendar3"></i>
          <span id="headerDate">MON, SEPTEMBER 14, 2026</span>
        </div>
        <div class="header-v-divider"></div>
        <div class="d-flex align-items-center gap-2 fs-3 fw-extrabold">
          <i class="bi bi-clock"></i>
          <span id="headerClock">10:23 AM</span>
        </div>
      </div>
    </header>

    <!-- MAIN DASHBOARD CONTENT -->
    <main class="queue-main-content">
      <div class="row g-3 h-100 align-items-stretch">

        <!-- LEFT: Waiting Queue Sidebar -->
        <div class="col-12 col-lg-3 h-100">
          <div class="queue-card h-100 d-flex flex-column">
            <div class="card-blue-header d-flex justify-content-between align-items-center">
              <div class="d-flex align-items-center gap-2 fw-bold text-uppercase fs-6">
                <i class="bi bi-people-fill"></i> Waiting Queue
              </div>
              <span class="badge bg-white text-primary rounded-pill px-3 py-1 fw-bold fs-7" id="queueCount">0
                WAITING</span>
            </div>

            <div class="waiting-list-scroll p-3 flex-grow-1" id="waitingList">
              <!-- Dynamic items generated by JS -->
            </div>
          </div>
        </div>

        <!-- CENTER: Hero Screen (Now Calling) -->
        <div class="col-12 col-lg-6 h-100">
          <div
            class="hero-calling-card h-100 text-center text-white d-flex flex-column justify-content-between align-items-center position-relative">

            <!-- Top Announcement Pill -->
            <div
              class="now-calling-pill rounded-pill px-5 py-3 text-white fw-extrabold text-uppercase d-inline-flex align-items-center gap-2">
              <i class="bi bi-megaphone-fill"></i> NOW CALLING
            </div>

            <!-- Center Display (Chevron Arrows & Token) -->
            <div class="my-auto w-100 position-relative py-3">
              <h1 class="hero-ticket-text" id="currentNumber">---</h1>
              <h2 class="hero-office-text" id="servingOffice">---</h2>
              <div class="divider-line mx-auto"></div>
            </div>

            <p class="proceed-notice fs-10 text-white mb-0 text-uppercase">
              Please proceed to the indicated office.
            </p>
          </div>
        </div>

        <!-- RIGHT: Office Status Grid (6 rows x 2 cols - Full Height Span) -->
        <div class="col-12 col-lg-3 h-100">
          <div class="queue-card h-100 d-flex flex-column p-2">
            <div class="card-blue-header d-flex justify-content-between align-items-center mb-2 p-2 flex-shrink-0">
              <div class="d-flex align-items-center gap-2 fw-bold text-uppercase fs-6">
                <i class="bi bi-building-fill"></i> Office Status
              </div>
              <span class="badge bg-white text-primary rounded-pill px-2 py-1 fw-bold" style="font-size: 0.65rem;" id="officeSubtitle">0 OFFICES</span>
            </div>

            <!-- Grid Container set to flex-grow-1 to take up all remaining vertical space -->
            <div class="row g-2 flex-grow-1" id="officeGrid" style="grid-template-rows: repeat(6, 1fr);">
              <!-- Dynamic 2-column office cards generated by JS -->
            </div>
          </div>
        </div>

      </div>
    </main>

    <!-- FOOTER STRIP WITH CAMPUS IMAGE BACKGROUND -->
    <footer
      class="queue-footer-strip d-flex align-items-center justify-content-between px-4 position-relative overflow-hidden">
      <!-- Background Campus Image Container -->
      <div class="footer-bg-image" style="background-image: url('<?= $baseUrl; ?>/assets/img/queue_footer.webp');"></div>
      <div class="footer-bg-overlay"></div>

      <!-- Center: College Motto / Branding -->
      <div class="text-center position-absolute start-50 translate-middle-x z-1">
        <span class="motto-script text-white">Your Success</span>
        <span class="motto-sub text-warning fw-extrabold">Our Commitment</span>
      </div>
    </footer>
  </div>
</div>

<script>
  /* =====================================================
     DATA CONFIGURATION (12 Offices Total)
     ===================================================== */
  const queueData = [
    { number: "R-024", office: "Registrar Office" },
    { number: "AC-015", office: "Accounting Office" },
    { number: "AD-008", office: "Admissions Office" },
    { number: "G-011", office: "Guidance Office" },
    { number: "L-012", office: "Library" },
    { number: "C-006", office: "School Clinic" },
    { number: "CA-018", office: "Cashier" },
    { number: "HR-004", office: "Human Resources" },
    { number: "IT-009", office: "IT Center" },
    { number: "SA-021", office: "Student Affairs" },
    { number: "VP-003", office: "VPAA Office" },
    { number: "OS-001", office: "OIC Dean Office" }
  ];

  const officeStatus = [
    { office: "Registrar Office", queue: "R-024", status: "SERVING", icon: "bi-file-earmark-text-fill", color: "text-primary bg-primary-subtle" },
    { office: "Accounting Office", queue: "AC-015", status: "SERVING", icon: "bi-calculator-fill", color: "text-success bg-success-subtle" },
    { office: "Admissions Office", queue: "AD-008", status: "SERVING", icon: "bi-mortarboard-fill", color: "text-warning bg-warning-subtle" },
    { office: "Guidance Office", queue: "G-011", status: "SERVING", icon: "bi-people-fill", color: "text-info bg-info-subtle" },
    { office: "School Clinic", queue: "C-006", status: "SERVING", icon: "bi-hospital-fill", color: "text-danger bg-danger-subtle" },
    { office: "Library", queue: "L-012", status: "SERVING", icon: "bi-book-fill", color: "text-secondary bg-secondary-subtle" },
    { office: "Cashier", queue: "CA-018", status: "SERVING", icon: "bi-cash-coin", color: "text-success bg-success-subtle" },
    { office: "Human Resources", queue: "HR-004", status: "SERVING", icon: "bi-briefcase-fill", color: "text-dark bg-light-subtle" },
    { office: "IT Center", queue: "IT-009", status: "SERVING", icon: "bi-laptop-fill", color: "text-primary bg-primary-subtle" },
    { office: "Student Affairs", queue: "SA-021", status: "SERVING", icon: "bi-person-badge-fill", color: "text-info bg-info-subtle" },
    { office: "VPAA Office", queue: "VP-003", status: "SERVING", icon: "bi-award-fill", color: "text-warning bg-warning-subtle" },
    { office: "OIC Dean Office", queue: "OS-001", status: "SERVING", icon: "bi-building-gear", color: "text-danger bg-danger-subtle" }
  ];

  let currentIndex = 0;
  const officesPerPage = 12;

  /* =====================================================
     VOICE ANNOUNCEMENT LOGIC
     ===================================================== */
  let singleFemaleVoice = null;

  function getBestFemaleVoice() {
    if (!('speechSynthesis' in window)) return null;
    const voices = window.speechSynthesis.getVoices();
    if (!voices || voices.length === 0) return null;

    const femaleNames = ["zira", "janny", "jenny", "samantha", "siri", "victoria", "karen", "aria", "ava", "emma", "hazel", "susan", "female", "google us english"];
    const maleNames = ["david", "mark", "george", "james", "richard", "male", "guy", "stefan"];

    let selected = voices.find(v => v.lang.startsWith('en') && femaleNames.some(fn => v.name.toLowerCase().includes(fn)));
    if (!selected) {
      selected = voices.find(v => v.lang.startsWith('en') && !maleNames.some(mn => v.name.toLowerCase().includes(mn)));
    }
    return selected || voices.find(v => v.lang.startsWith('en')) || voices[0];
  }

  function loadVoices() { singleFemaleVoice = getBestFemaleVoice(); }
  if ('speechSynthesis' in window) {
    window.speechSynthesis.onvoiceschanged = loadVoices;
    loadVoices();
  }

  function playBellDing() {
    try {
      const AudioContext = window.AudioContext || window.webkitAudioContext;
      if (!AudioContext) return;
      const ctx = new AudioContext();

      const osc1 = ctx.createOscillator();
      const gain1 = ctx.createGain();
      osc1.type = 'sine';
      osc1.frequency.setValueAtTime(659.25, ctx.currentTime);
      gain1.gain.setValueAtTime(0.3, ctx.currentTime);
      gain1.gain.exponentialRampToValueAtTime(0.0001, ctx.currentTime + 1.2);

      osc1.connect(gain1);
      gain1.connect(ctx.destination);
      osc1.start(ctx.currentTime);
      osc1.stop(ctx.currentTime + 1.2);

      const osc2 = ctx.createOscillator();
      const gain2 = ctx.createGain();
      osc2.type = 'sine';
      osc2.frequency.setValueAtTime(783.99, ctx.currentTime + 0.25);
      gain2.gain.setValueAtTime(0.35, ctx.currentTime + 0.25);
      gain2.gain.exponentialRampToValueAtTime(0.0001, ctx.currentTime + 1.6);

      osc2.connect(gain2);
      gain2.connect(ctx.destination);
      osc2.start(ctx.currentTime + 0.25);
      osc2.stop(ctx.currentTime + 1.6);
    } catch (e) {
      console.warn("Audio Context blocked until page interaction.", e);
    }
  }

  function speakNowCalling(ticketNumber, officeName) {
    if (!('speechSynthesis' in window)) return;
    window.speechSynthesis.cancel();
    if (!singleFemaleVoice) loadVoices();

    const spokenTicket = ticketNumber.split('').map(char => (char === '-' ? ' ' : char)).join(', ');
    const utterance = new SpeechSynthesisUtterance(`Now Calling, ${spokenTicket}, please proceed to ${officeName}.`);
    utterance.rate = 0.88;
    utterance.pitch = 1.1;
    utterance.lang = 'en-US';
    if (singleFemaleVoice) utterance.voice = singleFemaleVoice;

    setTimeout(() => window.speechSynthesis.speak(utterance), 500);
  }

  /* =====================================================
     DOM UPDATES
     ===================================================== */
  function updateCallingQueue() {
    if (!Array.isArray(queueData) || queueData.length === 0 || !queueData[currentIndex]) {
      const currentNumberEl = document.getElementById("currentNumber");
      const servingOfficeEl = document.getElementById("servingOffice");
      const queueCountEl = document.getElementById("queueCount");

      if (currentNumberEl) currentNumberEl.textContent = "---";
      if (servingOfficeEl) servingOfficeEl.textContent = "NO ACTIVE CALLS";
      if (queueCountEl) queueCountEl.textContent = "0 WAITING";
      return;
    }

    const current = queueData[currentIndex];

    const currentNumberEl = document.getElementById("currentNumber");
    const servingOfficeEl = document.getElementById("servingOffice");

    if (currentNumberEl) currentNumberEl.textContent = current.number || "---";
    if (servingOfficeEl) servingOfficeEl.textContent = current.office || "---";

    if (typeof playBellDing === "function") playBellDing();
    if (typeof speakNowCalling === "function") {
      speakNowCalling(current.number, current.office);
    }

    const waitingList = document.getElementById("waitingList");
    if (waitingList) {
      waitingList.innerHTML = "";
      const fragment = document.createDocumentFragment();

      for (let i = 1; i < queueData.length; i++) {
        const index = (currentIndex + i) % queueData.length;
        const queue = queueData[index];

        const item = document.createElement("div");
        item.className = "waiting-item d-flex justify-content-between align-items-center p-2 mb-2 rounded-3";
        item.innerHTML = `
        <span class="token-pill">${queue.number || "---"}</span>
        <span class="fw-bold text-dark small ms-2 text-truncate">${queue.office || "---"}</span>
      `;
        fragment.appendChild(item);
      }
      waitingList.appendChild(fragment);
    }

    const queueCountEl = document.getElementById("queueCount");
    if (queueCountEl) {
      queueCountEl.textContent = `${Math.max(0, queueData.length - 1)} WAITING`;
    }

    if (typeof updateOfficeStatus === "function") {
      updateOfficeStatus();
    }
  }

  function updateOfficeStatus() {
    const grid = document.getElementById("officeGrid");
    grid.innerHTML = "";

    const totalOffices = officeStatus.length;
    const currentTicket = queueData[currentIndex] ? queueData[currentIndex].number : "";

    for (let i = 0; i < totalOffices; i++) {
      const office = officeStatus[i];
      const isNowCalling = office.queue === currentTicket;

      const col = document.createElement("div");
      col.className = "col-6 h-100 d-flex";

      const displayStatus = isNowCalling ? "NOW CALLING" : office.status;
      const badgeColor = isNowCalling ? "text-warning" : "text-success";

      // Card set to h-100 & flex-grow-1 to stretch evenly across all 6 rows
      col.innerHTML = `
      <div class="office-status-card w-100 h-100 d-flex align-items-center gap-2 p-2 rounded-2 border ${isNowCalling ? 'active-calling border-warning bg-warning-subtle' : 'bg-white'}">
        <div class="icon-circle p-1 rounded-circle ${office.color} d-flex align-items-center justify-content-center" style="width:32px; height:32px; flex-shrink:0;">
          <i class="bi ${office.icon || 'bi-building'}" style="font-size:0.85rem;"></i>
        </div>
        <div class="overflow-hidden leading-tight flex-grow-1">
          <div class="fw-bold text-dark text-truncate" style="font-size:0.75rem; line-height:1.1;">${office.office}</div>
          <div class="fw-extrabold text-primary" style="font-size:0.85rem; line-height:1.1;">${office.queue}</div>
          <span class="status-indicator ${badgeColor} d-block text-truncate" style="font-size:0.6rem; line-height:1;">
            <i class="bi bi-circle-fill me-1" style="font-size:0.4rem;"></i>${displayStatus}
          </span>
        </div>
      </div>
    `;

      grid.appendChild(col);
    }

    document.getElementById("officeSubtitle").textContent = `${totalOffices} OFFICES`;
  }

  function updateClock() {
    const now = new Date();
    let hours = now.getHours();
    let minutes = now.getMinutes();
    const ampm = hours >= 12 ? "PM" : "AM";
    hours = hours % 12 || 12;
    minutes = minutes.toString().padStart(2, "0");

    document.getElementById("headerClock").textContent = `${hours}:${minutes} ${ampm}`;

    const options = { weekday: "short", month: "long", day: "numeric", year: "numeric" };
    document.getElementById("headerDate").textContent = now.toLocaleDateString("en-US", options).toUpperCase();
  }

  /* =====================================================
     INIT
     ===================================================== */
  updateClock();
  setInterval(updateClock, 1000);

  setTimeout(() => {
    updateCallingQueue();
    setInterval(() => {
      currentIndex = (currentIndex + 1) % queueData.length;
      updateCallingQueue();
    }, 10000);
  }, 300);
</script>

<?php require_once __DIR__ . '/../includes/footer.php'; ?>